module PGN
  # Shared FEN/EPD board-field parsing and serialization: the piece-placement
  # field, and the '-'-normalized castling/en-passant fields. {PGN::FEN} and
  # {PGN::EPD} both include this rather than each carrying their own copy.
  module PositionFields
    def castling=(val)
      @castling = val.nil? || val.empty? ? '-' : val
    end

    def en_passant=(val)
      @en_passant = val.nil? ? '-' : val
    end

    # @param board_fen [String] the FEN/EPD representation of the board
    def board_string=(board_fen)
      squares = board_fen.gsub(/\d/) { |match| '_' * match.to_i }
                         .split('/')
                         .map(&:chars)
                         .map { |row| row.map { |e| e == '_' ? nil : e } }
                         .reverse
                         .transpose
      self.board = PGN::Board.new(squares)
    end

    # @return [String] the FEN/EPD board-string portion
    def board_string
      board.fen_board_string
    end

    private

    # The player/castling-rights/en-passant args shared by FEN#to_position
    # and EPD#to_position (which differ only in halfmove/fullmove).
    def position_fields
      player = active == 'w' ? :white : :black
      castling_rights = castling.chars - ['-']
      ep = en_passant == '-' ? nil : en_passant
      [player, castling_rights, ep]
    end
  end

  # {PGN::FEN} is responsible for translating between strings in FEN
  # notation and an internal representation of the board.
  #
  # @see http://en.wikipedia.org/wiki/Forsyth-Edwards_Notation
  #   Forsyth-Edwards notation
  #
  # @!attribute board
  #   @return [PGN::Board] a {PGN::Board} object for the current board
  #     state
  #
  # @!attribute active
  #   @return ['w', 't'] the current player
  #
  # @!attribute castling
  #   @return [String] the castling availability
  #   @example
  #     "Kq" # white can castle kingside and black queenside
  #   @example
  #     "-"  # no one can castle
  #
  # @!attribute en_passant
  #   @return [String] the current en passant square
  #   @example
  #     "e3" # white just moved e2 -> e4
  #     "-"  # no current en passant square
  #
  # @!attribute halfmove
  #   @return [String] the halfmove clock
  #   @note This is the number of halfmoves since the last pawn advance or capture
  #
  # @!attribute fullmove
  #   @return [String] the fullmove counter
  #   @note The number of full moves. This is incremented after black
  #     plays.
  #
  class FEN
    include PositionFields

    # The FEN string representing the starting position in chess
    #
    INITIAL = 'rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1'.freeze

    attr_accessor :board, :active, :halfmove, :fullmove
    # `castling` and `en_passant` have custom writers in {PositionFields}
    # (normalize nil/empty to '-'), so expose readers here and rely on the
    # module for the writers, to avoid redefining the accessors generated by
    # attr_accessor (Lint/DuplicateMethods).
    attr_reader :castling, :en_passant

    # @return [PGN::FEN] a {PGN::FEN} object representing the starting
    #   position
    #
    def self.start
      PGN::FEN.new(INITIAL)
    end

    # @return [PGN::FEN] a {PGN::FEN} object with the given attributes
    #
    def self.from_attributes(attrs)
      fen = PGN::FEN.new
      attrs.each do |key, val|
        fen.send("#{key}=", val)
      end
      fen
    end

    # @param fen_string [String] a string in Forsyth-Edwards Notation
    #
    def initialize(fen_string = nil)
      return unless fen_string

      self.board_string,
        self.active,
        self.castling,
        self.en_passant,
        self.halfmove,
        self.fullmove = fen_string.split
    end

    # @return [PGN::Position] a {PGN::Position} representing the current
    #   position
    #
    def to_position
      player, castling_rights, ep = position_fields
      PGN::Position.new(board, player, castling_rights, ep, halfmove.to_i, fullmove.to_i)
    end

    # @return [String] the EPD string for this position (the first four FEN
    #   fields, dropping the halfmove/fullmove counters)
    #
    def to_epd
      PGN::EPD.new("#{board_string} #{active} #{castling} #{en_passant}").to_s
    end

    # @return [String] the FEN string
    # @example
    #   PGN::FEN.start.to_s #=> "rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1"
    #
    def to_s
      [
        board_string,
        active,
        castling,
        en_passant,
        halfmove,
        fullmove
      ].join(' ')
    end

    def inspect
      to_s
    end
  end
end
