#
# DO NOT MODIFY!!!!
# This file is automatically generated by Racc 1.8.1
# from Racc grammar file "pgn_parser.y".
#

require 'racc/parser.rb'
module PGN
  class PgnParser < Racc::Parser

module_eval(<<'...end pgn_parser.y/module_eval...', 'pgn_parser.y', 87)

  def parse(input)
    @lexer = PGN::Lexer.new(input)
    @input = input
    games = do_parse
    assign_pgn!(games)
    games
  end

  def next_token
    pair = @lexer.next_token_pair
    return [false, false] unless pair
    # Mutate the lexer's [type, value] pair in place rather than allocating
    # a second translated pair -- one array per token is the Racc floor.
    pair[0] = translate_type(pair[0])
    pair
  end

  private

  # Fold a move's trailing suffix (comments, NAGs, variations, in any
  # order) onto a MoveText. Multiple comments are concatenated with a
  # space after each is individually cleaned; NAGs are merged in order;
  # variations are collected in source order and then reversed, preserving
  # the legacy order the serializer and round-trip specs depend on.
  def build_move(notation, suffix)
    comment_parts = []
    nags = nil
    variations = []
    suffix.each do |kind, payload|
      case kind
      when :comment   then comment_parts << MoveText.clean_text(payload)
      when :nags       then nags = nags ? nags + payload : payload
      when :variation  then variations << payload
      end
    end
    comment = comment_parts.empty? ? nil : comment_parts.join(' ')
    MoveText.new(notation, nags, comment, variations.reverse)
  end

  # Punctuation tokens are racc'd by their literal character (taken from
  # PGN::Lexer::LITERAL_BYTES, the single source of truth for those
  # characters); everything else is racc'd by the upcased lexer symbol.
  # A complete frozen lookup keeps this a plain hash read for every token
  # instead of allocating two Strings (`to_s` + `upcase`) per token.
  TOKEN_TRANSLATIONS = PGN::Lexer::LITERAL_BYTES.values.to_h.merge(
    string: :STRING, comment: :COMMENT, game_termination: :GAME_TERMINATION,
    san_move: :SAN_MOVE, nag: :NAG, move_number: :MOVE_NUMBER, tag_name: :TAG_NAME
  ).freeze

  def translate_type(sym)
    TOKEN_TRANSLATIONS.fetch(sym) do
      raise "PGN::Lexer produced an unknown token type: #{sym.inspect}"
    end
  end

  # Slice the verbatim raw PGN text per game out of the original input using
  # the per-game content-start byte offsets recorded by the lexer.
  #
  # Game 0 spans from byte 0; game k (k >= 1) spans from its first
  # non-discarded token's offset; each game ends where the next game begins
  # (or at EOF for the last game). Leading/trailing discarded tokens (a
  # game's leading `%` comment, or the whitespace between games) fold into
  # the adjacent game's span, reproducing the legacy accumulator output.
  def assign_pgn!(games)
    starts = @lexer.game_starts
    total  = @input.bytesize
    games.each_with_index do |game, k|
      start = (k == 0) ? 0 : starts[k]
      fin   = (k + 1 < games.length) ? starts[k + 1] : total
      game[:pgn] = @input.byteslice(start...fin)
    end
  end
...end pgn_parser.y/module_eval...
##### State transition tables begin ###

racc_action_table = [
     2,    16,     7,    17,    21,    14,     6,    24,    21,     6,
    30,    24,    25,    16,    12,    17,    25,    14,    11,    18,
    26,    28 ]

racc_action_check = [
     1,    29,     2,    29,    17,    29,     4,    17,    19,     1,
    29,    19,    17,    10,    10,    10,    19,    10,     6,    11,
    18,    22 ]

racc_action_pointer = [
   nil,     0,     2,   nil,    -3,   nil,    10,   nil,   nil,   nil,
    10,    17,   nil,   nil,   nil,   nil,   nil,     1,    10,     5,
   nil,   nil,    15,   nil,   nil,   nil,   nil,   nil,   nil,    -2,
   nil ]

racc_action_default = [
    -1,   -23,   -23,    -2,    -8,    -4,   -23,    31,    -3,    -5,
   -23,   -23,    -7,    -9,   -10,   -11,   -12,   -13,   -23,   -14,
   -15,   -17,   -18,   -19,   -20,    -8,    -6,   -16,   -21,   -23,
   -22 ]

racc_goto_table = [
    10,     5,     1,    20,     9,    27,     3,     4,     8,    19,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,    29 ]

racc_goto_check = [
     6,     5,     1,    10,     5,    10,     2,     3,     4,     9,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,     6 ]

racc_goto_pointer = [
   nil,     2,     5,     6,     4,     0,    -4,   nil,   nil,    -8,
   -14,   nil,   nil ]

racc_goto_default = [
   nil,   nil,   nil,   nil,   nil,   nil,   nil,    13,    15,   nil,
   nil,    22,    23 ]

racc_reduce_table = [
  0, 0, :racc_error,
  0, 14, :_reduce_1,
  2, 14, :_reduce_2,
  2, 15, :_reduce_3,
  1, 16, :_reduce_4,
  2, 16, :_reduce_5,
  4, 18, :_reduce_6,
  2, 17, :_reduce_7,
  0, 19, :_reduce_8,
  2, 19, :_reduce_9,
  1, 20, :_reduce_10,
  1, 20, :_reduce_none,
  1, 20, :_reduce_12,
  1, 21, :_reduce_13,
  2, 21, :_reduce_14,
  1, 22, :_reduce_15,
  2, 22, :_reduce_16,
  1, 23, :_reduce_17,
  1, 23, :_reduce_18,
  1, 23, :_reduce_19,
  1, 24, :_reduce_20,
  2, 24, :_reduce_21,
  3, 25, :_reduce_22 ]

racc_reduce_n = 23

racc_shift_n = 31

racc_token_table = {
  false => 0,
  :error => 1,
  :STRING => 2,
  :COMMENT => 3,
  :GAME_TERMINATION => 4,
  :SAN_MOVE => 5,
  :NAG => 6,
  :MOVE_NUMBER => 7,
  :TAG_NAME => 8,
  "[" => 9,
  "]" => 10,
  "(" => 11,
  ")" => 12 }

racc_nt_base = 13

racc_use_result_var = true

Racc_arg = [
  racc_action_table,
  racc_action_check,
  racc_action_default,
  racc_action_pointer,
  racc_goto_table,
  racc_goto_check,
  racc_goto_default,
  racc_goto_pointer,
  racc_nt_base,
  racc_reduce_table,
  racc_token_table,
  racc_shift_n,
  racc_reduce_n,
  racc_use_result_var ]
Ractor.make_shareable(Racc_arg) if defined?(Ractor)

Racc_token_to_s_table = [
  "$end",
  "error",
  "STRING",
  "COMMENT",
  "GAME_TERMINATION",
  "SAN_MOVE",
  "NAG",
  "MOVE_NUMBER",
  "TAG_NAME",
  "\"[\"",
  "\"]\"",
  "\"(\"",
  "\")\"",
  "$start",
  "pgn_database",
  "pgn_game",
  "tag_section",
  "movetext_section",
  "tag_pair",
  "element_sequence",
  "element",
  "san_move_annotated",
  "move_suffix",
  "suffix_item",
  "annotation_list",
  "variation" ]
Ractor.make_shareable(Racc_token_to_s_table) if defined?(Ractor)

Racc_debug_parser = false

##### State transition tables end #####

# reduce 0 omitted

module_eval(<<'.,.,', 'pgn_parser.y', 9)
  def _reduce_1(val, _values, result)
     result = []
    result
  end
.,.,

module_eval(<<'.,.,', 'pgn_parser.y', 10)
  def _reduce_2(val, _values, result)
     result = val[0] << val[1]
    result
  end
.,.,

module_eval(<<'.,.,', 'pgn_parser.y', 15)
  def _reduce_3(val, _values, result)
            result = val[1].pop
        result = {
          tags:    val[0].reverse_each.with_object({}) { |pair, h| h.merge!(pair) },
          result:  result,
          moves:   val[1],
          pgn:     nil,
          comment: (@game_comment.tap { @game_comment = nil }),
        }

    result
  end
.,.,

module_eval(<<'.,.,', 'pgn_parser.y', 26)
  def _reduce_4(val, _values, result)
     result = [val[0]]
    result
  end
.,.,

module_eval(<<'.,.,', 'pgn_parser.y', 29)
  def _reduce_5(val, _values, result)
            # Left-recursive; the source-order array is reduced to the legacy
        # tag semantics in {pgn_game} (reverse, then merge with
        # first-occurrence-wins) so the whittle-order compatibility quirk is
        # a single explicit line instead of implicit in recursion direction.
        result = val[0] << val[1]

    result
  end
.,.,

module_eval(<<'.,.,', 'pgn_parser.y', 37)
  def _reduce_6(val, _values, result)
     result = { val[1] => val[2][1...-1] }
    result
  end
.,.,

module_eval(<<'.,.,', 'pgn_parser.y', 40)
  def _reduce_7(val, _values, result)
     result = val[0] << val[1]
    result
  end
.,.,

module_eval(<<'.,.,', 'pgn_parser.y', 43)
  def _reduce_8(val, _values, result)
     result = []
    result
  end
.,.,

module_eval(<<'.,.,', 'pgn_parser.y', 46)
  def _reduce_9(val, _values, result)
            result = val[1].nil? ? val[0] : val[0] << val[1]

    result
  end
.,.,

module_eval(<<'.,.,', 'pgn_parser.y', 50)
  def _reduce_10(val, _values, result)
     result = nil
    result
  end
.,.,

# reduce 11 omitted

module_eval(<<'.,.,', 'pgn_parser.y', 54)
  def _reduce_12(val, _values, result)
            # A standalone comment (not attached to a move) becomes the game
        # comment; the last such comment in the game wins.
        @game_comment = val[0]
        result = nil

    result
  end
.,.,

module_eval(<<'.,.,', 'pgn_parser.y', 61)
  def _reduce_13(val, _values, result)
     result = MoveText.new(val[0])
    result
  end
.,.,

module_eval(<<'.,.,', 'pgn_parser.y', 62)
  def _reduce_14(val, _values, result)
     result = build_move(val[0], val[1])
    result
  end
.,.,

module_eval(<<'.,.,', 'pgn_parser.y', 70)
  def _reduce_15(val, _values, result)
     result = [val[0]]
    result
  end
.,.,

module_eval(<<'.,.,', 'pgn_parser.y', 71)
  def _reduce_16(val, _values, result)
     result = val[0] << val[1]
    result
  end
.,.,

module_eval(<<'.,.,', 'pgn_parser.y', 74)
  def _reduce_17(val, _values, result)
     result = [:comment, val[0]]
    result
  end
.,.,

module_eval(<<'.,.,', 'pgn_parser.y', 75)
  def _reduce_18(val, _values, result)
     result = [:nags, val[0]]
    result
  end
.,.,

module_eval(<<'.,.,', 'pgn_parser.y', 76)
  def _reduce_19(val, _values, result)
     result = [:variation, val[0]]
    result
  end
.,.,

module_eval(<<'.,.,', 'pgn_parser.y', 79)
  def _reduce_20(val, _values, result)
     result = [val[0]]
    result
  end
.,.,

module_eval(<<'.,.,', 'pgn_parser.y', 80)
  def _reduce_21(val, _values, result)
     result = val[0] << val[1]
    result
  end
.,.,

module_eval(<<'.,.,', 'pgn_parser.y', 83)
  def _reduce_22(val, _values, result)
     result = val[1]
    result
  end
.,.,

def _reduce_none(val, _values, result)
  val[0]
end

  end   # class PgnParser
end   # module PGN
