require 'pgn'

# Helpers for order-independent variation comparison. The parser's
# `variation_list` rule is right-recursive, so a move's variations are stored
# in reverse of their PGN-text order; round-tripping flips that order each
# parse. We therefore compare variation trees as sorted signatures, and
# reference variations by notation rather than by index.
def node_sig(move)
  [move.notation, (move.variations || []).map { line_sig(_1) }.sort]
end

def line_sig(line)
  line.map { node_sig(_1) }
end

def tree_sig(game)
  game.moves.map { node_sig(_1) }
end

# This file was generated by the `rspec --init` command. Conventionally, all
# specs live under a `spec` directory, which RSpec adds to the `$LOAD_PATH`.
# Require this file using `require "spec_helper"` to ensure that it is only
# loaded once.
#
# See http://rubydoc.info/gems/rspec-core/RSpec/Core/Configuration
RSpec.configure do |config|
  config.run_all_when_everything_filtered = true
  config.filter_run :focus

  # Run specs in random order to surface order dependencies. If you find an
  # order dependency and want to debug it, you can fix the order by providing
  # the seed, which is printed after each run.
  #     --seed 1234
  config.order = 'random'
end
